const fs = require('fs')
const lines = fs.readFileSync('script.rb', 'utf-8').split('\n')
/* eslint-disable quote-props */
const nametags = {
  'Nanjo': 'Нанджо',
  'Kinzo': 'Кинзо',
  'Genji': 'Генджи',
  'Battler': 'Баттлер',
  'George': 'Джордж',
  'BEATRICE': 'Беатриче',
  'BERNKASTEL': 'Бернкастель',
  'Eva': 'Ева',
  'Gohda': 'Года',
  'Hideyoshi': 'Хидеёши',
  'Jessica': 'Джессика',
  'Kanon': 'Канон',
  'Kyrie': 'Кирие',
  'Krauss': 'Краусс',
  'Kumasawa': 'Кумасава',
  'Maria': 'Мария',
  'Natsuhi': 'Нацухи',
  'Rosa': 'Роза',
  'Rudolf': 'Рудольф',
  'Shannon': 'Шаннон',
  'LAMBDADELTA': 'Лямбдадельта',
  'Lucifer': 'Люцифер',
  'Leviathan': 'Лефиафан',
  'Satan': 'Сатана',
  'Belphegor': 'Бельфегор',
  'Mammon': 'Мамон',
  'Beelzebub': 'Вельзевул',
  'Asmodeus': 'Асмодей',
  'Ronove': 'Ронове',
  'Chiester410': 'Сиеста 410',
  'Chiester45': 'Сиеста 45',
  'Chiester00': 'Сиеста 00',
  'Chiester556': 'Сиеста 556',
  'Sakutarou': 'Сакутаро',
  'VIRGILIA': 'Виргилия',
  'Amakusa': 'Амакуза',
  'Ange': 'Энджи',
  'Kasumi': 'Касуми',
  'Kawabata': 'Кавабата',
  'Masayuki': 'Масаюки',
  'Okonogi': 'Оконоги',
  'Ootsuki': 'Ооцуки',
  'Sabakichi': 'Сабакичи',
  'Erika': 'Ерика',
  'Cornelia': 'Корнелия',
  'Dlanor': 'Дланор',
  'Gertrude': 'Гетртруда',
  'Furfur': 'Фурфур',
  'Zepar': 'Зепар',
  'FEATHERINE': 'Фезарин',
  'Will': 'Уиллард',
  'Lion': 'Лион',
  'Goat': 'Козлоголовый',
  'Gaap': 'Гаап',
  'EVA': 'Ева-Беатриче',
  'Tohya': 'Тойя',
  'Elder BEATRICE': 'Старшая Беатриче',
  'Clair': 'Клэр',
  'ANGE': 'Энджи-Беатриче',
  'Ikuko': 'Икуко',
  'Yukari': 'Юкари',
  'Saku': 'Саку',
  'Black Battler': 'Черный Баттлер',
  'Flauros': 'Флаурос',
  'PIECE': 'Пис',
  'Virgilius': 'Виргилиус'
}
/* eslint-enable quote-props */
for (let i = 0; i < lines.length; i++) {
  if (!lines[i].startsWith('s.ins 0x86')) continue
  for (const nt of Object.keys(nametags)) {
    lines[i] = lines[i].replace(`s.layout('${nt}@r`, `s.layout('${nametags[nt]}@r`)
  }
}
fs.writeFileSync('script.rb', lines.join('\n'), 'utf-8')
